insert into stock_names (ticker, name) values ('aapl', 'Apple');
insert into stock_names (ticker, name) values ('amzn', 'Amazon');
insert into stock_names (ticker, name) values ('bp', 'BP');
insert into stock_names (ticker, name) values ('coke', 'Coca-Cola');
insert into stock_names (ticker, name) values ('cost', 'Costco');
insert into stock_names (ticker, name) values ('cvs', 'CVS Health');
insert into stock_names (ticker, name) values ('cvx', 'Chevron');
insert into stock_names (ticker, name) values ('dpz', 'Dominos');
insert into stock_names (ticker, name) values ('googl', 'Google');
insert into stock_names (ticker, name) values ('hd', 'Home Depot');
insert into stock_names (ticker, name) values ('ibm', 'IBM');
insert into stock_names (ticker, name) values ('jnj', 'Johnson & Johnson');
insert into stock_names (ticker, name) values ('jpm', 'JPMorgan Chase');
insert into stock_names (ticker, name) values ('msft', 'Microsoft');
insert into stock_names (ticker, name) values ('mtb', 'M&T Bank');
insert into stock_names (ticker, name) values ('nflx', 'Netflix');
insert into stock_names (ticker, name) values ('tgt', 'Target');
insert into stock_names (ticker, name) values ('ulta', 'Ulta Beauty');
insert into stock_names (ticker, name) values ('v', 'Visa');
insert into stock_names (ticker, name) values ('wmt', 'Walmart');
